### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by macgyverkam** [XFox111/TabsAsideExtension#36]
Adding a card search function to filter by url and title.

**Comment by XFox111** [comment]
Hi. Thanks for your feedback!
Unfortunately, I don't think it will be a useful addition to the extension since there is a search in browser history list which does quite the exact thing. Besides, the extension was designed as a temporary tab sets storage (e.g. to move them aside, switch to another task and then come back to complete the task you've postponed)

If you're not agree with me, you can try to change my opinion by explaining why this feature must be implemented
